In [1]:
import numpy as np 
import pandas as pd
import tensorflow as tf
tf.__version__

'2.3.0'

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y)
dataset.head

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


<bound method NDFrame.head of       RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfPro

In [3]:
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [4]:
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [5]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


In [6]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
#building our model 
ann=tf.keras.models.Sequential()

In [8]:
#building input and hidden layer
ann.add(tf.keras.layers.Dense(units=5,activation='relu'))

In [9]:
#second layer
ann.add(tf.keras.layers.Dense(units=7,activation='relu'))

In [10]:
#output layer
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [11]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])# for binary classification nd for 
#non binary classification must be catergorical_crossentropy

In [12]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 0s 696us/step - loss: 0.6276 - accuracy: 0.7495
Epoch 2/100
250/250 [==============================] - 0s 760us/step - loss: 0.5145 - accuracy: 0.7986
Epoch 3/100
250/250 [==============================] - 0s 798us/step - loss: 0.4556 - accuracy: 0.8089
Epoch 4/100
250/250 [==============================] - 0s 784us/step - loss: 0.4321 - accuracy: 0.8130
Epoch 5/100
250/250 [==============================] - 0s 861us/step - loss: 0.4190 - accuracy: 0.8185
Epoch 6/100
250/250 [==============================] - 0s 806us/step - loss: 0.4083 - accuracy: 0.8198
Epoch 7/100
250/250 [==============================] - 0s 743us/step - loss: 0.4003 - accuracy: 0.8186
Epoch 8/100
250/250 [==============================] - 0s 741us/step - loss: 0.3949 - accuracy: 0.8190
Epoch 9/100
250/250 [==============================] - 0s 902us/step - loss: 0.3907 - accuracy: 0.8199
Epoch 10/100
250/250 [==============================] - 0s 696us/step - l

Epoch 80/100
250/250 [==============================] - 0s 922us/step - loss: 0.3343 - accuracy: 0.8659
Epoch 81/100
250/250 [==============================] - 0s 771us/step - loss: 0.3342 - accuracy: 0.8635
Epoch 82/100
250/250 [==============================] - 0s 705us/step - loss: 0.3339 - accuracy: 0.8662
Epoch 83/100
250/250 [==============================] - 0s 764us/step - loss: 0.3337 - accuracy: 0.8646
Epoch 84/100
250/250 [==============================] - 0s 795us/step - loss: 0.3334 - accuracy: 0.8648
Epoch 85/100
250/250 [==============================] - 0s 831us/step - loss: 0.3341 - accuracy: 0.8651
Epoch 86/100
250/250 [==============================] - 0s 742us/step - loss: 0.3339 - accuracy: 0.8633
Epoch 87/100
250/250 [==============================] - 0s 756us/step - loss: 0.3341 - accuracy: 0.8644
Epoch 88/100
250/250 [==============================] - 0s 795us/step - loss: 0.3337 - accuracy: 0.8659
Epoch 89/100
250/250 [==============================] - 0s 753us

In [13]:
print(ann.predict(sc.transform([[1,1,0,600,1,40,3,60000,2, 1, 1, 50000]]))>0.5)

[[False]]


In [14]:
#predicting the test results
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [15]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1511   84]
 [ 189  216]]


0.8635